### ISSUE TITLE
IoU ignore thresh only applied to noobj

### ISSUE THREAD

**Issue by lfleck** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#21]
Hi, 
can you explain why the IoU ignore threshold is only applied to the no-object mask, but not to the object mask (or why the no-object mask is not simply the inversion of the object mask in general):

[https://github.com/VCasecnikovs/Yet-Another-YOLOv4-Pytorch/blob/47b045014e6d7686fad7a6cbe3d3d3e5373a2b7e/model.py#L834](https://github.com/VCasecnikovs/Yet-Another-YOLOv4-Pytorch/blob/47b045014e6d7686fad7a6cbe3d3d3e5373a2b7e/model.py#L834)

I would have expected
`obj_mask[b[i], anchor_ious < ignore_thres, gj[i], gi[i]] = 0` in addition.

**Comment by VCasecnikovs** [comment]
Hello, when we are having target tensor, that means, that we are going to count the loss at the end. 
If mask is no object, but have enough IoU to be good, we shouldn't make this mask false, because the prediction was correct. By doing this trick we will have more detections on each object, which will lead to better accuracy, wrong detections we will be able to eliminate with NMS.
